- name: Enable NTP in timedatectl
  ansible.builtin.command: |
    timedatectl set-ntp true

- name: Ensure systemd-timesyncd is enabled and running
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
    enabled: yes

- name: Enable NTP in timedatectl
  ansible.builtin.command: |
    timedatectl set-local-rtc 0

- name: Set real time clock to UTC
  ansible.builtin.command: |
    hwclock --systohc --localtime

- name: Update distro
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - git
      - apt-transport-https
      - ca-certificates
      - gnupg
      - curl

- name: Set timezone to Europe/Paris
  become: true
  community.general.timezone:
    name: Europe/Paris
