deployment:
  replicas: 3
  resources:
    limits:
      memory: "128M"
    requests:
      memory: "64M"
  ports:
    - 3000
  image:
    repository: placeholder-repository
    name: placeholder-whanos-project
