---
- name: Download kubectl binary
  become: true
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Verify kubectl checksum
  become: true
  ansible.builtin.shell: |
    echo "$(curl -sL https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl.sha256) /usr/local/bin/kubectl" | sha256sum --check
  args:
    executable: /bin/bash
