jenkins:
  systemMessage: "Haha chapeau-chapeau"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Admin"
          password: "password"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrator"
            entries:
              - user: "admin"
            permissions:
              - "Overall/Administer"

jobs:
  - file: /var/lib/jenkins/job_dsl.groovy
