jenkins:
  systemMessage: "Haha chapeau-chapeau"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_USERNAME}"
          name: "Admin"
          password: "${JENKINS_ADMIN_PASSWORD}"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrator"
            entries:
              - user: "${JENKINS_ADMIN_USERNAME}"
            permissions:
              - "Overall/Administer"

jobs:
  - file: /var/lib/jenkins/job_dsl.groovy

credentials:
  system:
    domainCredentials:
      - credentials:
        - basicSSHUserPrivateKey:
            id: "git_ssh_key"
            description: "Default SSH key for git operations"
            scope: GLOBAL
            privateKeySource:
              directEntry:
                privateKey: "${SSH_PRIVATE_KEY}"
            username: "${SSH_USERNAME}"

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
  scriptApproval:
    approvedScriptHashes:
      - "SHA512:a0454f0041e2b6a09bbd4127d483bfe04dc56fc3904e23c7c69f7ebf2d8d65cbd487033afe3fb7816a3cb74550c8aaf8d99b34404e6d55276e2f9dc3200bcb15"
