---
- name: Deploy Jenkins CI Server with plugins
  hosts: jenkins_servers
  become: true
  vars:
    jenkins_port: 8080
    jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    jenkins_repo_url: deb https://pkg.jenkins.io/debian-stable binary/
    java_package: openjdk-17-jdk
    jenkins_home: /var/lib/jenkins
    plugins_file_remote: /tmp/plugins.txt

  pre_tasks:
    - name: Ensure gnupg and curl are installed (for key import)
      ansible.builtin.apt:
        name:
          - gnupg
          - curl
        state: present
        update_cache: yes

  tasks:
    - name: Install Java (required for Jenkins)
      ansible.builtin.apt:
        name: "{{ java_package }}"
        state: present

    - name: Add Jenkins repository key
      ansible.builtin.apt_key:
        url: "{{ jenkins_repo_key_url }}"
        state: present

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: "{{ jenkins_repo_url }}"
        state: present

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Ensure Jenkins service is enabled and started
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to start listening on port {{ jenkins_port }}
      ansible.builtin.wait_for:
        port: "{{ jenkins_port }}"
        timeout: 60

    - name: Upload plugins.txt file
      ansible.builtin.copy:
        src: ./plugins.txt
        dest: "{{ plugins_file_remote }}"
        owner: jenkins
        group: jenkins
        mode: '0644'

    - name: Install Jenkins plugins from plugins.txt as jenkins user
      ansible.builtin.command:
        cmd: "jenkins-plugin-cli --plugin-file {{ plugins_file_remote }}"
      become_user: jenkins
      environment:
        JENKINS_HOME: "{{ jenkins_home }}"
      register: plugin_install
      changed_when: "'Installed' in plugin_install.stdout or 'Updated' in plugin_install.stdout"

    - name: Restart Jenkins after plugin installation
      ansible.builtin.service:
        name: jenkins
        state: restarted

    - name: Print initial Jenkins admin password path
      ansible.builtin.debug:
        msg: "Jenkins is ready. Retrieve admin password using: sudo cat /var/lib/jenkins/secrets/initialAdminPassword"
