- name: Update all servers and install base packages
  hosts: all
  roles:
    - base

- name: Setup automation platform (Jenkins)
  hosts: hub-1
  vars:
    docker_registry_address: "registry.digitalocean.com/goofy-ah-cringe-registry"
  roles:
    - role: registry
      when: docker_registry_address | regex_search('^localhost')
    - role: jenkins
