- hosts: all
  roles:
    - base

- hosts: hub
  vars:
    registry_adress: "localhost"
    registry_port: 5000
    helm_version: "v3.19.0"
  roles:
    - geerlingguy.docker
    - geerlingguy.helm
    - jenkins
    - role: registry
      when: registry_adress == "localhost"

- hosts: k8s_control_plane
  vars:
    kubernetes_role: "control_plane"
    helm_version: "v3.19.0"
  roles:
    - geerlingguy.containerd
    - geerlingguy.kubernetes
    - geerlingguy.helm
    - dashboard

- hosts: k8s_worker
  vars:
    kubernetes_role: "node"
  roles:
    - geerlingguy.containerd
    - geerlingguy.kubernetes