- hosts: all
  roles:
        - base

- hosts: hub
  vars:
    jenkins_port: 8080
    registry_port: 5000
  roles:
        - geerlingguy.docker
        - jenkins
        - registry

- hosts: k8s
  vars:
    kubernetes_role: "control_plane"
  roles:
    - geerlingguy.containerd
    - geerlingguy.kubernetes