---
roles:
  - name: geerlingguy.docker
    version: 7.8.0

  - name: geerlingguy.helm
    version: 1.0.1

collections:
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: main
