apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: default
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  {{- if .Values.deployment.ports}}
  ports:
    {{- range .Values.deployment.ports }}
    - port: {{ . }}
      targetPort: {{ . }}
    {{- end }}
  {{- end}}
